<?php
$helper = $this->getHelper('GetIndexContent');
$player = $this->getHelper('ShowPlayer');
$stream = $this->getHelper('GetStreamParams');
?>
<!-- Контент -->
<div id="content">

    <!-- Левая калонка -->
    <div id="left_column">
        <div id="tag" class="t0">
          <?php echo $helper->getStyles('amount'); ?>
        </div>
        <div id="tag" class="t1" style="display:none;">
            <?php echo $helper->getStyles('rate'); ?>
        </div>
    </div>
    <!-- Конец левая калонка -->
    <!-- Правая калонка -->
    <div id="right_column">
        <div id="right_content">
            <div id="right_content_border_t"></div>
            <div id="right_content_border">
                <div id="radio_info">
                    <div id="radio_ico">
                        <img src="/images/<?php echo $this->channel['pic']; ?>" alt="" />
                    </div>
                    <div id="radio_info_text">
                        <h1><?php echo $this->channel['station'].' - '.$this->channel['channel'];?></h1>
                        <p>Битрейт: <span><?php echo $helper->getChannelStream($this->channel['id']); ?></span></p>
                        <p>Стиль: <span><?php echo $helper->getChannelStyles($this->channel['id']); ?></span></p>
                    </div>
                    <div id="radio_rating">
                        <p><span class="radio_rating"><b><?php echo $helper->getChannelPlace($this->channel['id']); ?></b> место в рейтинге</span></p>
                        <p>Количество слушателей: <span>4</span></p>
                        <p>Максимальное: <span>20</span></p>
                    </div>
                </div>
                <div id="radio_play">
<!--                    <a href="#" class="radio_play">Слушать радио</a>-->
                    <?php
                        $params = $stream->getParams($this->channel['best_stream']);
                        echo $player->showPlayer($params);
                    ?>
                    <a href="http://<?php echo $this->channel['www']; ?>" class="radio_url">www.<?php echo $this->channel['www']; ?></a>
                    <a style="cursor: pointer" class="radio_vote">Голосовать за радио</a>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $(".radio_vote").live('click', function () {
                                $.ajax({
                                    type:'POST',
                                    url:"/default/ajax/vote/format/html", //is needed to convert text to mp3
                                    contentType:'application/x-www-form-urlencoded; charset=utf8',
                                    success:function (data) {
                                        if (data == 'ok') {
                                            $(".radio_vote").html('Спасибо! Ваш голос учтен.');
                                        }
                                        else {
                                            $(".radio_vote").html('Вы уже голосовали сегодня.');
                                        }
                                    }, error:function (xhr, textStatus, errorThrown) {

                                    },
                                    data:{
                                        channel:<?php echo $this->channel['id']; ?>
                                    }
                                });
                            });
                        });
                    </script>
                </div>
                <div id="radio_text">
                    <p><?php echo $this->channel['ch_descr']; ?></p>
                    <p><?php echo $this->channel['st_descr']; ?></p>
                </div>
            </div>
            <div id="right_content_border_b"></div>
            <div class="baner">
                <a href="#"><img src="/images/baner2.gif" alt="" /></a>
            </div>
        </div>
    </div>
    <!-- Конец правая калонка -->
</div>
<!-- Конец контент -->