<?php
$helper = $this->getHelper('GetIndexContent');
$player = $this->getHelper('ShowPlayer');
$stream = $this->getHelper('GetStreamParams');
?>
<!-- Контент -->
<form style="display:none" name="playlist_form" action="/index/playlist" method="post" >
    <fieldset>
        <input name="playlist_data" id="playlist_data" value="<?php
        foreach ($this->styles as $style) {
            echo $style['id'].':';
        }
        ?>">
    </fieldset>
</form>
<div id="content">
    <!-- Шапка контента -->
    <div id="content_top">
        <div id="list">
            <a href="/index/style" class="list_radio">Cписок всех радиостанций</a>
            <a href="/index/asc" class="alphabetical">По алфавиту</a>
            <!--            <a href="#" class="price">Полный прайс-лист</a>-->
        </div>
        <div id="on_line_radio">
            <?php
            $i = 0;
            while ($i < 2) {
                $rand = $helper->getRandChannel();
                if ($rand) {
                    ?>
                    <div>
				<span>
					<img src="/images/<?php echo $rand['pic']?>" alt="" width="50px;" height="50px;"/>
				</span>

                        <p>
                            <a href="/index/channel/chid/<?php echo $rand['id']; ?>"><?php echo $rand['channel']; ?></a>
                            <b>
                                <?php echo $helper->getChannelStyles($rand['id']);?> |  <?php echo $helper->getChannelStream($rand['id']);?>
                            </b>
                        </p>
                    </div>
                    <?php
                    $i++;
                }
            }
            ?>
        </div>
        <div id="recommendation">
            наши рекомендации
        </div>
    </div>
    <div id="style_radio">
        <div class="style_bg_l"></div>
        <div class="style_bg_r"></div>
        <div class="tyle_radio_name" style="width:300px;">
           <br>
           Найдено станций: <i><?php echo count($this->styles); ?></i>
        </div>
        <?php if ( count($this->styles) ) {?>
        <a style="margin-top: 34px;">
			<span>
				<span id="make_playlist" class="buttom_radio">
					Загрузить playlist
				</span>
			</span>
        </a>
        <?php }?>
    </div>
    <script type="text/javascript">
        $(document).ready(function (){
            $("#make_playlist").live('click', function() {
                document.playlist_form.submit();
            });
        });
    </script>
    <!-- Конец шапка контента -->
    <!-- Левая калонка -->
    <div id="left_column" style="padding-right:14px;">
        <div  id="tag_menu">
            <?php echo $helper->getStyles('asc'); ?>
        </div>
    </div>
    <!-- Конец левая калонка -->
    <!-- Правая калонка -->
    <div id="right_column" style="width:725px;">
        <div id="radio_style_all">
        <?php
        if (isset($this->styles[0])) {
            foreach ($this->styles as $style) {
                ?>
                <span>
						<span>
							<span>
							 	<dl>
                                     <dt>
                                         <img src="/images/<?php echo $style['pic'];?>" alt="" width="50px" height="50px" />
                                     </dt>
                                     <dd>
                                         <a href="/index/channel/chid/<?php echo $style['id']; ?>"><?php echo $style['channel'];?></a>
                                         <p><?php echo $helper->getChannelStyles($style['id']); ?>
                                             <i><?php echo $style['bitrate']?> kbits <?php echo $style['format']; ?></i>
                                         </p>
                                     </dd>
                                 </dl>
								<div>
                                    <a href="http://<?php echo $style['www'];?>" class="url_radio"><?php echo $style['www'];?></a>
                                    <a  href="/index/channel/chid/<?php echo $style['id']; ?>" class="music"></a>
                                </div>
							</span>
						</span>
					</span>
                <?php
            }
        }
        else { ?>
            <h1>По запросу ничего не найдено... <a href="/index">Назад</a></h1>
        <?php
        }
        ?>

            <div class="baner">
                <a href="#"><img src="/images/baner2.gif" alt="" /></a>
            </div>
        </div>
    </div>
    <!-- Конец правая калонка -->
</div>
<!-- Конец контент -->

