<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
        html { height: 100% }
        body { height: 100%; margin: 0; padding: 0 }
        #map_canvas { height: 100% }
    </style>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmbg_9kC9U9_Yiq1qkN8U1HATzy92GNc0&sensor=true">
    </script>
    <script type="text/javascript">
        var geocoder;
        var map;
        var allMarkers = [];
        var myCenter = new google.maps.LatLng(53.902389, 27.555289);

        function initialize() {
            geocoder = new google.maps.Geocoder();
            var mapOptions = {
                center: myCenter,
                zoom: 12,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById("map_canvas"),
                mapOptions);
//                var marker = new google.maps.Marker({
//                position: map.getCenter(),
//                map: map,
//                title: 'Some marker'
//            });
            // bounds of the desired area
            var allowedBounds = new google.maps.LatLngBounds(

                new google.maps.LatLng(53.812628, 27.735705),
            new google.maps.LatLng(53.973745, 27.422938)
            );
            var lastValidCenter = map.getCenter();

            google.maps.event.addListener(map, 'center_changed', function() {

               var timer = window.setTimeout(function () {
                    if (allowedBounds.contains(map.getCenter())) {
                        // still within valid bounds, so save the last valid position
                        lastValidCenter = map.getCenter();
                        return;
                    }
                    // not valid anymore => return to last valid position
                    map.panTo(lastValidCenter);
                }, 1000);
                timer = null;
            });
        }

        function codeAddress() {
            var address = document.getElementById('address').value;
            geocoder.geocode( { 'address': address}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
//                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location,
                        name: address
                    });
                    allMarkers.push(marker);
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }

        function getMarkers() {
            var marker;
            console.log(allMarkers);
            while ( marker = allMarkers.pop() ) {
                alert( marker.name + ': ' + marker.position.lat() + ' ' + marker.position.lng() );
            }
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</head>
<body onload="initialize()">
<div>
    <input id="address" type="textbox" value="Проспект Независимости, Минск" size="120">
    <input type="button" value="Geocode" onclick="codeAddress()">
    <input type="button" value="Get markers" onclick="getMarkers()">
</div>
<div id="map_canvas" style="width:100%; height:100%;"></div>
</body>
</html>
