<h1 style="margin: 230px 0 20px 0;">Шаг первый</h1>
<p>
    Выберите радиостанцию, которая Вам по нраву. <br/>
    <br/>
    Это можно сделать следующими способами: <br/>
    <br>
    Способ 1. Выбрать станцию из списка "Новые станции"<br/>
    <br/>
    <img src="/images/howto_new.jpg" style="height:330px; width:430px;">
    <br/>
    Способ 2. Выбрать станцию из десятка случайных станций раздела "Мы рекомендуем"<br/>
    <br/>
    <img src="/images/howto_random.jpg" style="height:330px; width:430px;">
    <br/>
    <br/>
    Способ 3. Выбрать интересующее направление в облаке тегов (правая колонка),<br/>
    <br/>
    <img src="/images/howto_cloud.jpg" style="height:330px; width:450px;">
    <br/>
    <br/>
    а затем выбрать нужную станцию</br>
    <br/>
    <img src="/images/howto_channel.jpg" style="height:330px; width:450px;">
    <br/>
    <br/>
</p>
    <h1 style="margin: 30px 0 20px 0;">Шаг второй</h1>
    Нажать кнопку "Play" в проигрывателе <br/>
    <br/>
    <img src="/images/howto_play.jpg" style="height:330px; width:450px;">
    <br/>
    <br/>
