<div id="style_radio">
    <div class="style_text">
        Радиостанци<?php (count($this->channels) == 1) ? (print_r('я')) : (print_r('и')); ?> стиля
    </div>
    <div style="position: absolute; left:50%; top:12px;">
        <?php
        $channel_ids = array();
        foreach ($this->channels as $channel) {
            $channel_ids[] = $channel->getId();
        }
        $playlistUrl = $this->url(array(
        'controller' => 'index',
        'action'     => 'playlist',
        'id'        => $channel_ids
         )); ?>
        <a href="<?php echo $playlistUrl; ?>" style="float:left; margin-left: 10px; " title="Скачать playlist">Playlist</a>
    </div>
    <div class="tyle_radio_name">
        <i><?php echo $this->style->getStyle(); ?></i>
    </div>
</div>
<div id="radio_style_all">
    <?php
    foreach ($this->channels as $channel) {
        ?>
        <span>
            <span>
                <span>
                    <dl>
                        <dt>
                            <img alt="" src="/images/<?php echo $channel->getPic(); ?>"
                                 style="width:50px; height: 50px;">
                        </dt>
                        <dd>
                            <a href="/ajax/channel/id/<?php echo $channel->getId(); ?>"
                               class="ajax"><?php echo $channel->getChannel(); ?></a>

                            <p>
                                <?php
                                $styles = $channel->getStyles();
                                foreach ($styles as $style) {
                                    if (($style instanceof Application_Model_Style) && $style->getId()) {
                                        ?>
                                        <a href="/ajax/style/id/<?php echo $style->getId();?>"
                                           class="ajax"> <?php echo $style->getStyle(); ?> </a>
                                        <?php
                                    }
                                }
                                ?>
                                <i><?php echo $channel->getStreamObj()->getBitrate(); ?>
                                    kbits <?php echo  $channel->getStreamObj()->getFormat(); ?></i>
                            </p>
                        </dd>
                    </dl>
                    <div style="width:200%; height: 70px; position: absolute; bottom: 0%;">
                        <a class="ajax music" title="Слушать радио" style="float:left;  margin-left: 10px; margin-top: 17px;"
                           href="/ajax/channel/id/<?php echo $channel->getId(); ?>"></a>
                        <?php
                        $playlistUrl = $this->url(array(
                        'controller' => 'index',
                        'action'     => 'playlist',
                        'id'         => $channel->getId()
                         )); ?>
                        <a href="<?php echo $playlistUrl; ?>" class="price" style="float:left; margin-left: 10px; " title="Скачать playlist">Playlist</a>
                        <a class="url_radio" title="Перейти на сайт радиостанции" style="float:left;  margin-left: 10px; margin-top: 23px; font-size: 12px; color: #1689D1;"
                           href="http://<?php echo $channel->getStationObj()->getWww(); ?>" target="_blank">Сайт
                            радио</a>

                    </div>
                </span>
            </span>
		</span>
        <?php
    }
    ?>


</div>